let obj ={
	"questionList": [{
	"analysis": "<p>什么是社会主义、怎样建设社会主义，是邓小平在领导我国改革开放和现代化建设这一新的革命过程中，不断提出和反复思考的首要的基本的理论问题。</p>",
	"analysisType": -1,
	"answerTime": 2,
	"avgAnswerTime": 36,
	"avgCorrectRate": "94.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "A",
	"favorite": 0,
	"mainNodeName": "邓小平理论的基本问题",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>什么是马克思主义，怎样坚持和发展马克思主义</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 1,
		"optionContent": "<p>什么是社会主义，怎样建设社会主义</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>什么是小康社会，怎样建设小康社会</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>什么是和谐社会，怎样建设和谐社会</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "B",
	"questionContent": "<p>邓小平理论围绕的主题是（ ）</p>",
	"questionId": 1226197,
	"questionSource": "全国-0907真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 1,
	"studentAnswer": "B",
	"studentScore": 2.0
}, {
	"analysis": "<p>1992年年初，邓小平在南方谈话中对社会主义本质作了总结性理论概括：“社会主义的本质，是解放生产力，发展生产力，消灭剥削，消除两极分化，最终达到共同富裕。”</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 12,
	"avgCorrectRate": "85.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "A",
	"favorite": 0,
	"mainNodeName": "邓小平理论的基本问题",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">毛泽东</font></span></p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">周恩来</font></span></p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">刘少奇</font></span></p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 1,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">邓小平</font></span></p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "D",
	"questionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">新中国成立后明确提出社会主义本质论断的是（ ）</font></span></p>",
	"questionId": 1226206,
	"questionSource": "北京市-1810真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 2,
	"studentAnswer": "D",
	"studentScore": 2.0
}, {
	"analysis": "<p>1992年年初，邓小平在南方谈话中对社会主义本质作了总结性理论概括：“社会主义的本质，是解放生产力，发展生产力，消灭剥削，消除两极分化，最终达到共同富裕。”</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 8,
	"avgCorrectRate": "91.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "A",
	"favorite": 0,
	"mainNodeName": "邓小平理论的基本问题",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>发展生产力&nbsp; &nbsp;</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>消灭剥削</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>巩固公有制&nbsp;&nbsp;</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 1,
		"optionContent": "<p>实现共同富裕</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "D",
	"questionContent": "<p>社会主义的最终目标是（ ）</p>",
	"questionId": 1226204,
	"questionSource": "全国-1307真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 3,
	"studentAnswer": "D",
	"studentScore": 2.0
}, {
	"analysis": "<p>解放思想，实事求是，是我们党的思想路线。十一届三中全会作出了把党和国家工作重点转移到社会主义现代化建设上来的战略决策，提出了一系列有利于增强党的团结和调动一切积极因素的方针政策，标志着党重新确立了马克思主义的思想路线。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 13,
	"avgCorrectRate": "68.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "C",
	"favorite": 0,
	"mainNodeName": "解放思想、实事求是的思想路线",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>坚持社会主义</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>坚持党的领导</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>以经济建设为中心</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 1,
		"optionContent": "<p>​解放思想，实事求是<br></p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "D",
	"questionContent": "<p>我们党的思想路线是（ ）</p>",
	"questionId": 1218437,
	"questionSource": "模拟题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 4,
	"studentAnswer": "D",
	"studentScore": 2.0
}, {
	"analysis": "<p>社会主义初级阶段，就是指我国在生产力落后、商品经济不发达条件下建设社会主义必然要经历的特定阶段，即从我国进入社会主义到基本实现社会主义现代化的整个历史阶段。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 14,
	"avgCorrectRate": "81.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "D",
	"favorite": 0,
	"mainNodeName": "社会主义初级阶段理论",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">我国向共产主义过渡的阶段</font></span></p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 1,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">我国社会主义的不发达阶段</font></span></p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">全面建成小康社会的阶段</font></span></p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">社会主义社会的准备阶段</font></span></p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "B",
	"questionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">社会主义初级阶段就是（ ）</font></span></p>",
	"questionId": 1225951,
	"questionSource": "北京市-1810真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 5,
	"studentAnswer": "B",
	"studentScore": 2.0
}, {
	"analysis": "<p>党的十三大提出了党在社会主义初级阶段的基本路线，即领导和团结全国各族人民，以经济建设为中心，坚持四项基本原则，坚持改革开放，自力更生，艰苦创业，为把我国建设成为富强民主文明的社会主义现代化国家而奋斗。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 15,
	"avgCorrectRate": "72.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "A",
	"favorite": 0,
	"mainNodeName": "党在社会主义初级阶段的基本路线",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>党的建设</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 1,
		"optionContent": "<p>经济建设</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>巩固社会主义制度</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>发展社会主义民主政治</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "B",
	"questionContent": "<p>社会主义初级阶段党的中心工作是（ ）</p>",
	"questionId": 1225417,
	"questionSource": "全国-0910真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 6,
	"studentAnswer": "B",
	"studentScore": 2.0
}, {
	"analysis": "<p>“一个中心、两个基本点”是基本路线最主要的内容，是实现社会主义现代化奋斗目标的基本途径。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 10,
	"avgCorrectRate": "90.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "党在社会主义初级阶段的基本路线",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>五位一体</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 1,
		"optionContent": "<p>一个中心，两个基本点</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>三严三实</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>四个全面</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "B",
	"questionContent": "<p>党在社会主义初级阶段基本路线的简明概括是（ ）</p>",
	"questionId": 1225424,
	"questionSource": "全国-1704真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 7,
	"studentAnswer": "B",
	"studentScore": 2.0
}, {
	"analysis": "<p>社会主义的根本任务是发展生产力。社会主义革命是为了解放生产力，发展生产力。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 10,
	"avgCorrectRate": "80.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "A",
	"favorite": 0,
	"mainNodeName": "社会主义的根本任务",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>最终达到共同富裕</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>以阶级斗争为纲</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>实现“两个一百年”的目标</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 1,
		"optionContent": "<p>解放和发展生产力</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "D",
	"questionContent": "<p>社会主义的根本任务是（ ）</p>",
	"questionId": 1207160,
	"questionSource": "全国-1810真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 8,
	"studentAnswer": "D",
	"studentScore": 2.0
}, {
	"analysis": "<p>邓小平“科学技术是第一生产力”的论断，反映了科学技术在当代发展的新形势和对我国现代化建设的新要求。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 10,
	"avgCorrectRate": "80.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "D",
	"favorite": 0,
	"mainNodeName": "社会主义的根本任务",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>毛泽东</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 1,
		"optionContent": "<p>邓小平</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>习近平</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>​江泽民<br></p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "B",
	"questionContent": "<p>“科学技术是第一生产力”论断的提出者是（ ）</p>",
	"questionId": 1218621,
	"questionSource": "模拟题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 9,
	"studentAnswer": "B",
	"studentScore": 2.0
}, {
	"analysis": "<p>1987年4月，邓小平第一次提出了分“三步走”基本实现现代化的战略。同年10月，党的十三大把邓小平“三步走”的发展战略构想确定下来。我国经济建设的战略部署大体上分三步走：第一步，从1981年到1990年实现国民生产总值比1980年翻一番，解决人民的温饱问题；第二步，从1991年到20世纪末，使国民生产总值再翻一番，达到小康水平；第三步，到21世纪中叶，国民生产总值再翻两番，达到中等发达国家水平，基本实现现代化。然后在这个基础上继续前进。</p>",
	"analysisType": -1,
	"answerTime": 2,
	"avgAnswerTime": 15,
	"avgCorrectRate": "90.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "“三步走”战略",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>实现国民生产总值比1950年翻一番，解决人民的温饱问题</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>到20世纪末期，使国民生产总值再增长一倍，人民生活达到小康水平</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 1,
		"optionContent": "<p>到21世纪中叶，人均国民生产总值达到中等发达国家水平，人民生活比较富裕，基本实现现代化</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>到建党一百周年时，使国民经济更加发展，各项制度更加完善</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "C",
	"questionContent": "<p>邓小平1987年接见西班牙客人时，正式提出“三步走”战略构想，其中第三步是（ ）</p>",
	"questionId": 1226230,
	"questionSource": "全国-1804真题-第6题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 10,
	"studentAnswer": "C",
	"studentScore": 2.0
}, {
	"analysis": "<p>1987年4月，邓小平第一次提出了分“三步走”基本实现现代化的战略。同年10月，党的十三大把邓小平“三步走”的发展战略构想确定下来。我国经济建设的战略部署大体上分三步走：第一步，从1981年到1990年实现国民生产总值比1980年翻一番，解决人民的温饱问题；第二步，从1991年到20世纪末，使国民生产总值再翻一番，达到小康水平；第三步，到21世纪中叶，国民生产总值再翻两番，达到中等发达国家水平，基本实现现代化。然后在这个基础上继续前进。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 7,
	"avgCorrectRate": "94.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "“三步走”战略",
	"optionList": [{
		"correct": 1,
		"optionContent": "<p>解决人民的温饱问题</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>让人民生活比较宽裕</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>达到小康水平&nbsp; &nbsp;&nbsp;</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>使人民生活比较富裕</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "A",
	"questionContent": "<p>根据邓小平的“三步走”发展战略，第一步是（ ）</p>",
	"questionId": 1226231,
	"questionSource": "全国-1310真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 11,
	"studentAnswer": "A",
	"studentScore": 2.0
}, {
	"analysis": "<p>党的十一届三中全会作出了把党和国家工作中心转移到经济建设上来、实行改革开放的历史性决策，开启了中国特色社会主义建设波澜壮阔的历史新征程。尽管改革是一场革命，但它不是也不允许否定和抛弃我们建立起来的社会主义基本制度，它是社会主义制度的自我完善和发展。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 13,
	"avgCorrectRate": "91.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "改革开放理论",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>对原有体制细枝末节的修补&nbsp;</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>解决社会基本矛盾的一般性变革</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>一个阶级推翻另一个阶级的政治革命&nbsp;</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 1,
		"optionContent": "<p>社会主义制度的自我完善和发展</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "D",
	"questionContent": "<p>始于十一届三中全会的改革是（ ）</p>",
	"questionId": 1228256,
	"questionSource": "北京市-1604真题-第24题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 12,
	"studentAnswer": "D",
	"studentScore": 2.0
}, {
	"analysis": "<p>社会主义市场经济理论的要点有：一是计划经济和市场经济不是划分社会制度的标志，计划经济不等于社会主义，市场经济也不等于资本主义；二是计划和市场都是经济手段，对经济活动的调节各有优势和长处，社会主义实行市场经济要把两者结合起来；三是市场经济作为资源配置的一种方式本身不具有制度属性，可以和不同的社会制度结合；从而表现出不同的性质。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 22,
	"avgCorrectRate": "75.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "B",
	"favorite": 0,
	"mainNodeName": "社会主义市场经济理论",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p>是区分社会主义和资本主义的标志</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>属于社会基本制度的范畴</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 1,
		"optionContent": "<p>是资源配置的不同方式</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>是经济增长的不同方式</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "C",
	"questionContent": "<p>在社会主义市场经济理论中，计划经济和市场经济（ ）</p>",
	"questionId": 1230863,
	"questionSource": "北京市-1604真题-第25题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 13,
	"studentAnswer": "C",
	"studentScore": 2.0
}, {
	"analysis": "<p>台湾问题是国内战争遗留下来的问题，属于中国的内政，不容许外国干涉。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 6,
	"avgCorrectRate": "94.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "“一国两制”",
	"optionList": [{
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">国际政治问题</font></span></p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 1,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">中国的内政问题</font></span></p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">国际经济问题</font></span></p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">中国的外交问题</font></span></p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "B",
	"questionContent": "<p class=\"MsoNormal\"><span style=\"mso-spacerun:'yes';font-family:微软雅黑;font-size:10.5000pt;mso-font-kerning:1.0000pt;\"><font face=\"微软雅黑\">台湾问题从根本上讲是（ ）</font></span></p>",
	"questionId": 1230881,
	"questionSource": "北京市-1810真题-第1题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 14,
	"studentAnswer": "B",
	"studentScore": 2.0
}, {
	"analysis": "<p>坚持一个中国，这是“和平统一、一国两制”的核心，是发展两岸关系和实现和平统一的基础。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 7,
	"avgCorrectRate": "92.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "“一国两制”",
	"optionList": [{
		"correct": 1,
		"optionContent": "<p>一个中国原则</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>增强综合国力</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>扩大两岸经济文化交流</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>绝不承诺放弃武力</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "A",
	"questionContent": "<p>我国实现和平统一的基础和前提是（ ）</p>",
	"questionId": 1230895,
	"questionSource": "全国-1804真题-第15题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 15,
	"studentAnswer": "A",
	"studentScore": 2.0
}, {
	"analysis": "<p>加强党的建设，是我们党领导人民取得革命和建设胜利的一个法宝。要加强党的思想建设、组织建设、作风建设。</p>",
	"analysisType": -1,
	"answerTime": 1,
	"avgAnswerTime": 10,
	"avgCorrectRate": "95.0%",
	"avgScore": 0.0,
	"canAnswer": 1,
	"correct": 1,
	"errorProneAnswer": "",
	"favorite": 0,
	"mainNodeName": "中国问题的关键在于党",
	"optionList": [{
		"correct": 1,
		"optionContent": "<p>党的建设</p>",
		"optionTitle": "A",
		"sequence": 0
	}, {
		"correct": 0,
		"optionContent": "<p>法治建设</p>",
		"optionTitle": "B",
		"sequence": 1
	}, {
		"correct": 0,
		"optionContent": "<p>生态建设</p>",
		"optionTitle": "C",
		"sequence": 2
	}, {
		"correct": 0,
		"optionContent": "<p>民生建设</p>",
		"optionTitle": "D",
		"sequence": 3
	}],
	"questionAnswer": "A",
	"questionContent": "<p>加强（ ）是我们党领导人民取得革命和建设胜利的一个法宝。</p>",
	"questionId": 1214589,
	"questionSource": "模拟题",
	"questionType": "SINGLE_CHOICE",
	"score": 2.0,
	"sequence": 16,
	"studentAnswer": "A",
	"studentScore": 2.0
}],
	"total": 16,
	"totalSubQuestionNum": 16
}